### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by bobhenl** [heyxmirko/Simple-Wifi-Password-Grabber#1]
Hey, I think something is really so much broken here. Could you fix it please? But maybe it's only on my side, not sure, would be great if we could talk about it, cause I don't know how to fix it, it's so difficult for me. 

And btw... Due to this idea I think that you're so great dev, could I learn from you?

**Comment by heyxmirko** [comment]
Thanks for reporting. **I just missed "/ wpg /" in the route.**
 Everything is fine now

**Comment by bobhenl** [comment]
Hey, great that you found this issue, but I feel there's broken something else too that's need fix. I don't exactly know why it doesn't work, maybe you can contact me on disvord bobhenl#0255

**Comment by heyxmirko** [comment]
What exactly doesn't work? You need to describe the problem or send me the error message.
Btw... I sent you a friend request on discord.
